version: '3.9'

services:
  backend:
    image: backend-nestjs    
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-api
    ports:
      - "3001:3001"            
    env_file:
      - .env                    
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:7               
    container_name: mongo-db
    ports:
      - "27017:27017"            
    environment:
      MONGO_INITDB_DATABASE: scrum-squads
      MONGO_INITDB_ROOT_USERNAME: api_user
      MONGO_INITDB_ROOT_PASSWORD: Piobello5
    volumes:
      - mongo-data:/data/db    

volumes:
  mongo-data:
